# create a local .env file with the following properties:
#
# POSTGRES_USER=__username__
# POSTGRES_PASSWORD=__pass__
#
# DATABASE_URL="postgresql://__username__:__pass__@local_pgdb:5432/quotes?schema=public"
#
# PGADMIN_DEFAULT_EMAIL=username@domain.com
# PGADMIN_DEFAULT_PASSWORD=__pass__
#

version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}" 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}" 
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-tailwind
    ports:
      - '3000:3000'
    volumes:
      - .:/src/app
      - next-modules:/node_modules
      - /.next

volumes:
  local_pgdata:
  pgadmin-data:
  next-modules:

